services:
  genai-latex-proofreader-service:
    image: genai-latex-proofreader-docker
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/repo_root

    entrypoint: "tail -f /dev/null"

    working_dir: /repo_root

    hostname: genai-latex-proofreader
