name: "ci: Run automated tests"

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

permissions:
  contents: read

env:
  TERM: xterm-color

jobs:
  ci-run-tests:
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build docker images
        run: |
          (cd .devcontainer/latex; make build)

      - name: Check static code checking (mypy)
        run: |
          (cd .devcontainer/latex; make in-docker/run-make MAKE_TASK="run-mypy")

      - name: Run unit tests
        run: |
          (cd .devcontainer/latex; make in-docker/run-make MAKE_TASK="run-unit-tests")

      - name: Run e2e test and proofread example paper
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          (cd .devcontainer/latex; make in-docker/run-make MAKE_TASK="run-e2e-test-proofread-example-paper")

          # listing all files in output directory
          find proofreading-report/.
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Save proofreading report as artifact
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: example-proofreading-report
          path: proofreading-report/


